/* Generated by Pyrex 0.9.5.1a on Tue Jun 12 09:57:32 2007 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
__PYX_EXTERN_C double pow(double, double);
#include "numpy/arrayobject.h"
#include "myrand.h"
#include "OpenGL/gl.h"
#include "OpenGL/glext.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from molGL */

static PyTypeObject *__pyx_ptype_5molGL_ndarray = 0;
static PyArrayObject *__pyx_k2;
static PyArrayObject *__pyx_k3;
static PyArrayObject *__pyx_k4;
static PyArrayObject *__pyx_k5;
static PyArrayObject *__pyx_k6;


/* Implementation of molGL */


static PyObject *__pyx_n_GL_TEXTURE0_ARB;
static PyObject *__pyx_n_GL_TEXTURE1_ARB;
static PyObject *__pyx_n_numpy;
static PyObject *__pyx_n_MolDraw;
static PyObject *__pyx_n_MolDrawShadow;
static PyObject *__pyx_n_MolDrawHalo;
static PyObject *__pyx_n_MolDrawOnTexture;
static PyObject *__pyx_n_molDrawSticks;

static PyObject *__pyx_n_Exception;
static PyObject *__pyx_n_len;
static PyObject *__pyx_n_allclose;

static PyObject *__pyx_k7p;

static char (__pyx_k7[]) = "conf must be a sequence of 3 dimensional coordinates";

static PyObject *__pyx_f_5molGL_MolDraw(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5molGL_MolDraw(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyArrayObject *__pyx_v_coords = 0;
  PyArrayObject *__pyx_v_radii = 0;
  PyArrayObject *__pyx_v_textures = 0;
  PyArrayObject *__pyx_v_colors = 0;
  PyArrayObject *__pyx_v_clipplane = 0;
  PyArrayObject *__pyx_v_exclude = 0;
  PyArrayObject *__pyx_v_indices = 0;
  int __pyx_v_i;
  int __pyx_v_index;
  int __pyx_v_numindices;
  int __pyx_v_numexclude;
  int __pyx_v_stride1;
  int __pyx_v_stride2;
  int (*__pyx_v_idx);
  int (*__pyx_v_excl);
  int __pyx_v_clipping;
  float (*__pyx_v_vert);
  float (*__pyx_v_rad);
  float (*__pyx_v_col);
  float (*__pyx_v_tex);
  float (*__pyx_v_clip);
  float __pyx_v_x;
  float __pyx_v_y;
  float __pyx_v_z;
  float __pyx_v_r;
  int __pyx_v_noindices;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  int __pyx_5;
  static char *__pyx_argnames[] = {"coords","radii","textures","colors","clipplane","exclude","indices",0};
  __pyx_v_indices = __pyx_k2;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOOOOO|O", __pyx_argnames, &__pyx_v_coords, &__pyx_v_radii, &__pyx_v_textures, &__pyx_v_colors, &__pyx_v_clipplane, &__pyx_v_exclude, &__pyx_v_indices)) return 0;
  Py_INCREF(__pyx_v_coords);
  Py_INCREF(__pyx_v_radii);
  Py_INCREF(__pyx_v_textures);
  Py_INCREF(__pyx_v_colors);
  Py_INCREF(__pyx_v_clipplane);
  Py_INCREF(__pyx_v_exclude);
  Py_INCREF(__pyx_v_indices);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_coords), __pyx_ptype_5molGL_ndarray, 1, "coords")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_radii), __pyx_ptype_5molGL_ndarray, 1, "radii")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_textures), __pyx_ptype_5molGL_ndarray, 1, "textures")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_colors), __pyx_ptype_5molGL_ndarray, 1, "colors")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_clipplane), __pyx_ptype_5molGL_ndarray, 1, "clipplane")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_exclude), __pyx_ptype_5molGL_ndarray, 1, "exclude")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_indices), __pyx_ptype_5molGL_ndarray, 1, "indices")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":47 */
  __pyx_v_vert = ((float (*))__pyx_v_coords->data);

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":48 */
  __pyx_v_col = ((float (*))__pyx_v_colors->data);

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":49 */
  __pyx_v_rad = ((float (*))__pyx_v_radii->data);

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":50 */
  __pyx_v_tex = ((float (*))__pyx_v_textures->data);

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":52 */
  __pyx_1 = (__pyx_v_coords->nd != 2);
  if (__pyx_1) {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":53 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_Exception); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
    Py_INCREF(__pyx_k7p);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_k7p);
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_4, 0, 0);
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":54 */
  __pyx_1 = ((__pyx_v_coords->dimensions[1]) == 3);
  if (__pyx_1) {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":55 */
    __pyx_v_stride1 = ((__pyx_v_coords->strides[0]) / (sizeof(float )));

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":56 */
    __pyx_v_stride2 = ((__pyx_v_coords->strides[1]) / (sizeof(float )));
    goto __pyx_L3;
  }
  /*else*/ {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":58 */
    __pyx_v_stride1 = ((__pyx_v_coords->strides[1]) / (sizeof(float )));

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":59 */
    __pyx_v_stride2 = ((__pyx_v_coords->strides[0]) / (sizeof(float )));
  }
  __pyx_L3:;

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":61 */
  __pyx_1 = __pyx_v_indices == Py_None;
  if (__pyx_1) {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":62 */
    __pyx_1 = ((__pyx_v_coords->dimensions[1]) == 3);
    if (__pyx_1) {
      __pyx_v_numindices = (__pyx_v_coords->dimensions[0]);
      goto __pyx_L5;
    }
    /*else*/ {
      __pyx_v_numindices = (__pyx_v_coords->dimensions[1]);
    }
    __pyx_L5:;

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":64 */
    __pyx_v_noindices = 0;
    goto __pyx_L4;
  }
  /*else*/ {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":66 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L1;}
    Py_INCREF(((PyObject *)__pyx_v_indices));
    PyTuple_SET_ITEM(__pyx_3, 0, ((PyObject *)__pyx_v_indices));
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_1 = PyInt_AsLong(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_v_numindices = __pyx_1;

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":67 */
    __pyx_v_idx = ((int (*))__pyx_v_indices->data);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":68 */
    __pyx_v_noindices = 1;
  }
  __pyx_L4:;

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":70 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_2, __pyx_n_allclose); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_4 = PyInt_FromLong(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}
  Py_INCREF(((PyObject *)__pyx_v_clipplane));
  PyTuple_SET_ITEM(__pyx_2, 0, ((PyObject *)__pyx_v_clipplane));
  PyTuple_SET_ITEM(__pyx_2, 1, __pyx_4);
  __pyx_4 = 0;
  __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_1 = PyObject_IsTrue(__pyx_4); if (__pyx_1 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_5 = (!__pyx_1);
  if (__pyx_5) {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":71 */
    __pyx_v_clipping = 1;

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":72 */
    __pyx_v_clip = ((float (*))__pyx_v_clipplane->data);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":73 */
    __pyx_v_excl = ((int (*))__pyx_v_exclude->data);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":74 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
    __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
    Py_INCREF(((PyObject *)__pyx_v_exclude));
    PyTuple_SET_ITEM(__pyx_2, 0, ((PyObject *)__pyx_v_exclude));
    __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_1 = PyInt_AsLong(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_v_numexclude = __pyx_1;
    goto __pyx_L6;
  }
  /*else*/ {
    __pyx_v_clipping = 0;
  }
  __pyx_L6:;

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":77 */
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_numindices; ++__pyx_v_i) {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":78 */
    __pyx_5 = (__pyx_v_noindices == 0);
    if (__pyx_5) {
      __pyx_v_index = __pyx_v_i;
      goto __pyx_L9;
    }
    /*else*/ {
      __pyx_v_index = (__pyx_v_idx[__pyx_v_i]);
    }
    __pyx_L9:;

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":81 */
    __pyx_v_x = (__pyx_v_vert[((__pyx_v_index * __pyx_v_stride1) + (__pyx_v_stride2 * 0))]);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":82 */
    __pyx_v_y = (__pyx_v_vert[((__pyx_v_index * __pyx_v_stride1) + (__pyx_v_stride2 * 1))]);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":83 */
    __pyx_v_z = (__pyx_v_vert[((__pyx_v_index * __pyx_v_stride1) + (__pyx_v_stride2 * 2))]);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":84 */
    __pyx_v_r = (__pyx_v_rad[__pyx_v_index]);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":85 */
    __pyx_1 = (__pyx_v_clipping == 1);
    if (__pyx_1) {
      __pyx_1 = (((((__pyx_v_x * (__pyx_v_clip[0])) + (__pyx_v_y * (__pyx_v_clip[1]))) + (__pyx_v_z * (__pyx_v_clip[2]))) + (__pyx_v_clip[3])) < 0);
    }
    if (__pyx_1) {
      goto __pyx_L7;
      goto __pyx_L10;
    }
    __pyx_L10:;

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":86 */
    glColor3f((__pyx_v_col[((__pyx_v_index * 3) + 0)]),(__pyx_v_col[((__pyx_v_index * 3) + 1)]),(__pyx_v_col[((__pyx_v_index * 3) + 2)]));

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":87 */
    glTexCoord2f((__pyx_v_tex[((__pyx_v_index * 2) + 0)]),(__pyx_v_tex[((__pyx_v_index * 2) + 1)]));

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":88 */
    glNormal3f(1,1,__pyx_v_r);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":89 */
    glVertex3f(__pyx_v_x,__pyx_v_y,__pyx_v_z);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":90 */
    glNormal3f((-1),1,__pyx_v_r);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":91 */
    glVertex3f(__pyx_v_x,__pyx_v_y,__pyx_v_z);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":92 */
    glNormal3f((-1),(-1),__pyx_v_r);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":93 */
    glVertex3f(__pyx_v_x,__pyx_v_y,__pyx_v_z);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":94 */
    glNormal3f(1,(-1),__pyx_v_r);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":95 */
    glVertex3f(__pyx_v_x,__pyx_v_y,__pyx_v_z);
    __pyx_L7:;
  }

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":97 */
  __pyx_5 = (__pyx_v_clipping == 1);
  if (__pyx_5) {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":98 */
    for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_numexclude; ++__pyx_v_i) {

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":99 */
      __pyx_v_index = (__pyx_v_excl[__pyx_v_i]);

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":100 */
      __pyx_v_x = (__pyx_v_vert[((__pyx_v_index * __pyx_v_stride1) + (__pyx_v_stride2 * 0))]);

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":101 */
      __pyx_v_y = (__pyx_v_vert[((__pyx_v_index * __pyx_v_stride1) + (__pyx_v_stride2 * 1))]);

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":102 */
      __pyx_v_z = (__pyx_v_vert[((__pyx_v_index * __pyx_v_stride1) + (__pyx_v_stride2 * 2))]);

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":103 */
      __pyx_v_r = (__pyx_v_rad[__pyx_v_index]);

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":104 */
      glColor3f((__pyx_v_col[((__pyx_v_index * 3) + 0)]),(__pyx_v_col[((__pyx_v_index * 3) + 1)]),(__pyx_v_col[((__pyx_v_index * 3) + 2)]));

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":105 */
      glTexCoord2f((__pyx_v_tex[((__pyx_v_index * 2) + 0)]),(__pyx_v_tex[((__pyx_v_index * 2) + 1)]));

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":106 */
      glNormal3f(1,1,__pyx_v_r);

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":107 */
      glVertex3f(__pyx_v_x,__pyx_v_y,__pyx_v_z);

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":108 */
      glNormal3f((-1),1,__pyx_v_r);

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":109 */
      glVertex3f(__pyx_v_x,__pyx_v_y,__pyx_v_z);

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":110 */
      glNormal3f((-1),(-1),__pyx_v_r);

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":111 */
      glVertex3f(__pyx_v_x,__pyx_v_y,__pyx_v_z);

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":112 */
      glNormal3f(1,(-1),__pyx_v_r);

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":113 */
      glVertex3f(__pyx_v_x,__pyx_v_y,__pyx_v_z);
    }
    goto __pyx_L11;
  }
  __pyx_L11:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("molGL.MolDraw");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_coords);
  Py_DECREF(__pyx_v_radii);
  Py_DECREF(__pyx_v_textures);
  Py_DECREF(__pyx_v_colors);
  Py_DECREF(__pyx_v_clipplane);
  Py_DECREF(__pyx_v_exclude);
  Py_DECREF(__pyx_v_indices);
  return __pyx_r;
}

static PyObject *__pyx_k8p;

static char (__pyx_k8[]) = "conf must be a sequence of 3 dimensional coordinates";

static PyObject *__pyx_f_5molGL_MolDrawShadow(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5molGL_MolDrawShadow(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyArrayObject *__pyx_v_coords = 0;
  PyArrayObject *__pyx_v_radii = 0;
  PyArrayObject *__pyx_v_clipplane = 0;
  PyArrayObject *__pyx_v_exclude = 0;
  PyArrayObject *__pyx_v_indices = 0;
  int __pyx_v_i;
  int __pyx_v_index;
  int __pyx_v_numindices;
  int __pyx_v_numexclude;
  int __pyx_v_stride1;
  int __pyx_v_stride2;
  int (*__pyx_v_idx);
  int (*__pyx_v_excl);
  float (*__pyx_v_vert);
  float (*__pyx_v_rad);
  float (*__pyx_v_clip);
  float __pyx_v_x;
  float __pyx_v_y;
  float __pyx_v_z;
  float __pyx_v_r;
  int __pyx_v_noindices;
  int __pyx_v_clipping;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  int __pyx_5;
  static char *__pyx_argnames[] = {"coords","radii","clipplane","exclude","indices",0};
  __pyx_v_indices = __pyx_k3;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOOO|O", __pyx_argnames, &__pyx_v_coords, &__pyx_v_radii, &__pyx_v_clipplane, &__pyx_v_exclude, &__pyx_v_indices)) return 0;
  Py_INCREF(__pyx_v_coords);
  Py_INCREF(__pyx_v_radii);
  Py_INCREF(__pyx_v_clipplane);
  Py_INCREF(__pyx_v_exclude);
  Py_INCREF(__pyx_v_indices);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_coords), __pyx_ptype_5molGL_ndarray, 1, "coords")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_radii), __pyx_ptype_5molGL_ndarray, 1, "radii")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_clipplane), __pyx_ptype_5molGL_ndarray, 1, "clipplane")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_exclude), __pyx_ptype_5molGL_ndarray, 1, "exclude")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_indices), __pyx_ptype_5molGL_ndarray, 1, "indices")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":121 */
  __pyx_v_vert = ((float (*))__pyx_v_coords->data);

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":122 */
  __pyx_v_rad = ((float (*))__pyx_v_radii->data);

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":124 */
  __pyx_1 = (__pyx_v_coords->nd != 2);
  if (__pyx_1) {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":125 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_Exception); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}
    Py_INCREF(__pyx_k8p);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_k8p);
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_4, 0, 0);
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":126 */
  __pyx_1 = ((__pyx_v_coords->dimensions[1]) == 3);
  if (__pyx_1) {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":127 */
    __pyx_v_stride1 = ((__pyx_v_coords->strides[0]) / (sizeof(float )));

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":128 */
    __pyx_v_stride2 = ((__pyx_v_coords->strides[1]) / (sizeof(float )));
    goto __pyx_L3;
  }
  /*else*/ {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":130 */
    __pyx_v_stride1 = ((__pyx_v_coords->strides[1]) / (sizeof(float )));

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":131 */
    __pyx_v_stride2 = ((__pyx_v_coords->strides[0]) / (sizeof(float )));
  }
  __pyx_L3:;

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":133 */
  __pyx_1 = __pyx_v_indices == Py_None;
  if (__pyx_1) {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":134 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 134; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 134; goto __pyx_L1;}
    Py_INCREF(((PyObject *)__pyx_v_coords));
    PyTuple_SET_ITEM(__pyx_3, 0, ((PyObject *)__pyx_v_coords));
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 134; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_1 = PyInt_AsLong(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 134; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_v_numindices = __pyx_1;

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":135 */
    __pyx_v_noindices = 0;
    goto __pyx_L4;
  }
  /*else*/ {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":137 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 137; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 137; goto __pyx_L1;}
    Py_INCREF(((PyObject *)__pyx_v_indices));
    PyTuple_SET_ITEM(__pyx_3, 0, ((PyObject *)__pyx_v_indices));
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 137; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_1 = PyInt_AsLong(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 137; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_v_numindices = __pyx_1;

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":138 */
    __pyx_v_idx = ((int (*))__pyx_v_indices->data);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":139 */
    __pyx_v_noindices = 1;
  }
  __pyx_L4:;

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":141 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 141; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_2, __pyx_n_allclose); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 141; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_4 = PyInt_FromLong(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 141; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 141; goto __pyx_L1;}
  Py_INCREF(((PyObject *)__pyx_v_clipplane));
  PyTuple_SET_ITEM(__pyx_2, 0, ((PyObject *)__pyx_v_clipplane));
  PyTuple_SET_ITEM(__pyx_2, 1, __pyx_4);
  __pyx_4 = 0;
  __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 141; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_1 = PyObject_IsTrue(__pyx_4); if (__pyx_1 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 141; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_5 = (!__pyx_1);
  if (__pyx_5) {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":142 */
    __pyx_v_clipping = 1;

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":143 */
    __pyx_v_clip = ((float (*))__pyx_v_clipplane->data);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":144 */
    __pyx_v_excl = ((int (*))__pyx_v_exclude->data);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":145 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
    __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
    Py_INCREF(((PyObject *)__pyx_v_exclude));
    PyTuple_SET_ITEM(__pyx_2, 0, ((PyObject *)__pyx_v_exclude));
    __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_1 = PyInt_AsLong(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_v_numexclude = __pyx_1;
    goto __pyx_L5;
  }
  /*else*/ {
    __pyx_v_clipping = 0;
  }
  __pyx_L5:;

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":148 */
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_numindices; ++__pyx_v_i) {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":149 */
    __pyx_5 = (__pyx_v_noindices == 0);
    if (__pyx_5) {
      __pyx_v_index = __pyx_v_i;
      goto __pyx_L8;
    }
    /*else*/ {
      __pyx_v_index = (__pyx_v_idx[__pyx_v_i]);
    }
    __pyx_L8:;

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":151 */
    __pyx_v_x = (__pyx_v_vert[((__pyx_v_index * __pyx_v_stride1) + (__pyx_v_stride2 * 0))]);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":152 */
    __pyx_v_y = (__pyx_v_vert[((__pyx_v_index * __pyx_v_stride1) + (__pyx_v_stride2 * 1))]);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":153 */
    __pyx_v_z = (__pyx_v_vert[((__pyx_v_index * __pyx_v_stride1) + (__pyx_v_stride2 * 2))]);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":154 */
    __pyx_v_r = (__pyx_v_rad[__pyx_v_index]);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":155 */
    __pyx_1 = (__pyx_v_clipping == 1);
    if (__pyx_1) {
      __pyx_1 = (((((__pyx_v_x * (__pyx_v_clip[0])) + (__pyx_v_y * (__pyx_v_clip[1]))) + (__pyx_v_z * (__pyx_v_clip[2]))) + (__pyx_v_clip[3])) < 0);
    }
    if (__pyx_1) {
      goto __pyx_L6;
      goto __pyx_L9;
    }
    __pyx_L9:;

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":156 */
    glNormal3f(1,1,__pyx_v_r);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":157 */
    glVertex3f(__pyx_v_x,__pyx_v_y,__pyx_v_z);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":158 */
    glNormal3f((-1),1,__pyx_v_r);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":159 */
    glVertex3f(__pyx_v_x,__pyx_v_y,__pyx_v_z);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":160 */
    glNormal3f((-1),(-1),__pyx_v_r);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":161 */
    glVertex3f(__pyx_v_x,__pyx_v_y,__pyx_v_z);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":162 */
    glNormal3f(1,(-1),__pyx_v_r);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":163 */
    glVertex3f(__pyx_v_x,__pyx_v_y,__pyx_v_z);
    __pyx_L6:;
  }

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":165 */
  __pyx_5 = (__pyx_v_clipping == 1);
  if (__pyx_5) {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":166 */
    for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_numexclude; ++__pyx_v_i) {

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":167 */
      __pyx_v_index = (__pyx_v_excl[__pyx_v_i]);

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":168 */
      __pyx_v_x = (__pyx_v_vert[((__pyx_v_index * __pyx_v_stride1) + (__pyx_v_stride2 * 0))]);

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":169 */
      __pyx_v_y = (__pyx_v_vert[((__pyx_v_index * __pyx_v_stride1) + (__pyx_v_stride2 * 1))]);

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":170 */
      __pyx_v_z = (__pyx_v_vert[((__pyx_v_index * __pyx_v_stride1) + (__pyx_v_stride2 * 2))]);

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":171 */
      __pyx_v_r = (__pyx_v_rad[__pyx_v_index]);

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":172 */
      glNormal3f(1,1,__pyx_v_r);

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":173 */
      glVertex3f(__pyx_v_x,__pyx_v_y,__pyx_v_z);

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":174 */
      glNormal3f((-1),1,__pyx_v_r);

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":175 */
      glVertex3f(__pyx_v_x,__pyx_v_y,__pyx_v_z);

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":176 */
      glNormal3f((-1),(-1),__pyx_v_r);

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":177 */
      glVertex3f(__pyx_v_x,__pyx_v_y,__pyx_v_z);

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":178 */
      glNormal3f(1,(-1),__pyx_v_r);

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":179 */
      glVertex3f(__pyx_v_x,__pyx_v_y,__pyx_v_z);
    }
    goto __pyx_L10;
  }
  __pyx_L10:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("molGL.MolDrawShadow");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_coords);
  Py_DECREF(__pyx_v_radii);
  Py_DECREF(__pyx_v_clipplane);
  Py_DECREF(__pyx_v_exclude);
  Py_DECREF(__pyx_v_indices);
  return __pyx_r;
}

static PyObject *__pyx_k9p;

static char (__pyx_k9[]) = "conf must be a sequence of 3 dimensional coordinates";

static PyObject *__pyx_f_5molGL_MolDrawHalo(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5molGL_MolDrawHalo(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyArrayObject *__pyx_v_coords = 0;
  PyArrayObject *__pyx_v_radii = 0;
  float __pyx_v_halo_size;
  PyArrayObject *__pyx_v_clipplane = 0;
  PyArrayObject *__pyx_v_exclude = 0;
  PyArrayObject *__pyx_v_indices = 0;
  int __pyx_v_i;
  int __pyx_v_index;
  int __pyx_v_numindices;
  int __pyx_v_numexclude;
  int __pyx_v_stride1;
  int __pyx_v_stride2;
  int (*__pyx_v_idx);
  int (*__pyx_v_excl);
  float (*__pyx_v_vert);
  float (*__pyx_v_rad);
  float (*__pyx_v_clip);
  int __pyx_v_noindices;
  int __pyx_v_clipping;
  float __pyx_v_r;
  float __pyx_v_s;
  PyObject *__pyx_v_x;
  PyObject *__pyx_v_y;
  PyObject *__pyx_v_z;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  int __pyx_5;
  unsigned int __pyx_6;
  float __pyx_7;
  float __pyx_8;
  float __pyx_9;
  static char *__pyx_argnames[] = {"coords","radii","halo_size","clipplane","exclude","indices",0};
  __pyx_v_indices = __pyx_k4;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOfOO|O", __pyx_argnames, &__pyx_v_coords, &__pyx_v_radii, &__pyx_v_halo_size, &__pyx_v_clipplane, &__pyx_v_exclude, &__pyx_v_indices)) return 0;
  Py_INCREF(__pyx_v_coords);
  Py_INCREF(__pyx_v_radii);
  Py_INCREF(__pyx_v_clipplane);
  Py_INCREF(__pyx_v_exclude);
  Py_INCREF(__pyx_v_indices);
  __pyx_v_x = Py_None; Py_INCREF(Py_None);
  __pyx_v_y = Py_None; Py_INCREF(Py_None);
  __pyx_v_z = Py_None; Py_INCREF(Py_None);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_coords), __pyx_ptype_5molGL_ndarray, 1, "coords")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 181; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_radii), __pyx_ptype_5molGL_ndarray, 1, "radii")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 181; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_clipplane), __pyx_ptype_5molGL_ndarray, 1, "clipplane")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 181; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_exclude), __pyx_ptype_5molGL_ndarray, 1, "exclude")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 181; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_indices), __pyx_ptype_5molGL_ndarray, 1, "indices")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 181; goto __pyx_L1;}

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":189 */
  __pyx_v_vert = ((float (*))__pyx_v_coords->data);

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":190 */
  __pyx_v_rad = ((float (*))__pyx_v_radii->data);

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":191 */
  __pyx_v_s = (__pyx_v_halo_size * 2.5);

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":193 */
  __pyx_1 = (__pyx_v_coords->nd != 2);
  if (__pyx_1) {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":194 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_Exception); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 194; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 194; goto __pyx_L1;}
    Py_INCREF(__pyx_k9p);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_k9p);
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 194; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_4, 0, 0);
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 194; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":195 */
  __pyx_1 = ((__pyx_v_coords->dimensions[1]) == 3);
  if (__pyx_1) {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":196 */
    __pyx_v_stride1 = ((__pyx_v_coords->strides[0]) / (sizeof(float )));

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":197 */
    __pyx_v_stride2 = ((__pyx_v_coords->strides[1]) / (sizeof(float )));
    goto __pyx_L3;
  }
  /*else*/ {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":199 */
    __pyx_v_stride1 = ((__pyx_v_coords->strides[1]) / (sizeof(float )));

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":200 */
    __pyx_v_stride2 = ((__pyx_v_coords->strides[0]) / (sizeof(float )));
  }
  __pyx_L3:;

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":202 */
  __pyx_1 = __pyx_v_indices == Py_None;
  if (__pyx_1) {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":203 */
    __pyx_1 = ((__pyx_v_coords->dimensions[1]) == 3);
    if (__pyx_1) {
      __pyx_v_numindices = (__pyx_v_coords->dimensions[0]);
      goto __pyx_L5;
    }
    /*else*/ {
      __pyx_v_numindices = (__pyx_v_coords->dimensions[1]);
    }
    __pyx_L5:;

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":205 */
    __pyx_v_noindices = 0;
    goto __pyx_L4;
  }
  /*else*/ {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":207 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 207; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 207; goto __pyx_L1;}
    Py_INCREF(((PyObject *)__pyx_v_indices));
    PyTuple_SET_ITEM(__pyx_3, 0, ((PyObject *)__pyx_v_indices));
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 207; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_1 = PyInt_AsLong(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 207; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_v_numindices = __pyx_1;

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":208 */
    __pyx_v_idx = ((int (*))__pyx_v_indices->data);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":209 */
    __pyx_v_noindices = 1;
  }
  __pyx_L4:;

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":211 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 211; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_2, __pyx_n_allclose); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 211; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_4 = PyInt_FromLong(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 211; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 211; goto __pyx_L1;}
  Py_INCREF(((PyObject *)__pyx_v_clipplane));
  PyTuple_SET_ITEM(__pyx_2, 0, ((PyObject *)__pyx_v_clipplane));
  PyTuple_SET_ITEM(__pyx_2, 1, __pyx_4);
  __pyx_4 = 0;
  __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 211; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_1 = PyObject_IsTrue(__pyx_4); if (__pyx_1 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 211; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_5 = (!__pyx_1);
  if (__pyx_5) {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":212 */
    __pyx_v_clipping = 1;

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":213 */
    __pyx_v_clip = ((float (*))__pyx_v_clipplane->data);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":214 */
    __pyx_v_excl = ((int (*))__pyx_v_exclude->data);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":215 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 215; goto __pyx_L1;}
    __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 215; goto __pyx_L1;}
    Py_INCREF(((PyObject *)__pyx_v_exclude));
    PyTuple_SET_ITEM(__pyx_2, 0, ((PyObject *)__pyx_v_exclude));
    __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 215; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_1 = PyInt_AsLong(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 215; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_v_numexclude = __pyx_1;
    goto __pyx_L6;
  }
  /*else*/ {
    __pyx_v_clipping = 0;
  }
  __pyx_L6:;

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":218 */
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_numindices; ++__pyx_v_i) {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":219 */
    __pyx_5 = (__pyx_v_noindices == 0);
    if (__pyx_5) {
      __pyx_v_index = __pyx_v_i;
      goto __pyx_L9;
    }
    /*else*/ {
      __pyx_v_index = (__pyx_v_idx[__pyx_v_i]);
    }
    __pyx_L9:;

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":222 */
    __pyx_3 = PyFloat_FromDouble((__pyx_v_vert[((__pyx_v_index * __pyx_v_stride1) + (__pyx_v_stride2 * 0))])); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 222; goto __pyx_L1;}
    Py_DECREF(__pyx_v_x);
    __pyx_v_x = __pyx_3;
    __pyx_3 = 0;

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":223 */
    __pyx_2 = PyFloat_FromDouble((__pyx_v_vert[((__pyx_v_index * __pyx_v_stride1) + (__pyx_v_stride2 * 1))])); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 223; goto __pyx_L1;}
    Py_DECREF(__pyx_v_y);
    __pyx_v_y = __pyx_2;
    __pyx_2 = 0;

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":224 */
    __pyx_4 = PyFloat_FromDouble((__pyx_v_vert[((__pyx_v_index * __pyx_v_stride1) + (__pyx_v_stride2 * 2))])); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 224; goto __pyx_L1;}
    Py_DECREF(__pyx_v_z);
    __pyx_v_z = __pyx_4;
    __pyx_4 = 0;

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":225 */
    __pyx_v_r = (__pyx_v_rad[__pyx_v_index]);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":226 */
    __pyx_1 = (__pyx_v_clipping == 1);
    if (__pyx_1) {
      __pyx_3 = PyFloat_FromDouble((__pyx_v_clip[0])); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 226; goto __pyx_L1;}
      __pyx_2 = PyNumber_Multiply(__pyx_v_x, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 226; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      __pyx_4 = PyFloat_FromDouble((__pyx_v_clip[1])); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 226; goto __pyx_L1;}
      __pyx_3 = PyNumber_Multiply(__pyx_v_y, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 226; goto __pyx_L1;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      __pyx_4 = PyNumber_Add(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 226; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      __pyx_2 = PyFloat_FromDouble((__pyx_v_clip[2])); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 226; goto __pyx_L1;}
      __pyx_3 = PyNumber_Multiply(__pyx_v_z, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 226; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      __pyx_2 = PyNumber_Add(__pyx_4, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 226; goto __pyx_L1;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      __pyx_4 = PyFloat_FromDouble((__pyx_v_clip[3])); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 226; goto __pyx_L1;}
      __pyx_3 = PyNumber_Add(__pyx_2, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 226; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 226; goto __pyx_L1;}
      if (PyObject_Cmp(__pyx_3, __pyx_2, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 226; goto __pyx_L1;}
      __pyx_1 = __pyx_1 < 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_2); __pyx_2 = 0;
    }
    if (__pyx_1) {
      goto __pyx_L7;
      goto __pyx_L10;
    }
    __pyx_L10:;

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":228 */
    __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_GL_TEXTURE1_ARB); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 228; goto __pyx_L1;}
    __pyx_6 = PyInt_AsUnsignedLongMask(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 228; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    glMultiTexCoord2fARB(__pyx_6,(__pyx_v_r + __pyx_v_s),(((__pyx_v_r + __pyx_v_s) * (__pyx_v_r + __pyx_v_s)) / ((__pyx_v_s * __pyx_v_s) + ((2 * __pyx_v_r) * __pyx_v_s))));

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":230 */
    glTexCoord2f(1,1);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":231 */
    __pyx_7 = PyFloat_AsDouble(__pyx_v_x); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 231; goto __pyx_L1;}
    __pyx_8 = PyFloat_AsDouble(__pyx_v_y); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 231; goto __pyx_L1;}
    __pyx_9 = PyFloat_AsDouble(__pyx_v_z); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 231; goto __pyx_L1;}
    glVertex3f(__pyx_7,__pyx_8,__pyx_9);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":232 */
    glTexCoord2f((-1),1);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":233 */
    __pyx_7 = PyFloat_AsDouble(__pyx_v_x); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 233; goto __pyx_L1;}
    __pyx_8 = PyFloat_AsDouble(__pyx_v_y); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 233; goto __pyx_L1;}
    __pyx_9 = PyFloat_AsDouble(__pyx_v_z); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 233; goto __pyx_L1;}
    glVertex3f(__pyx_7,__pyx_8,__pyx_9);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":234 */
    glTexCoord2f((-1),(-1));

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":235 */
    __pyx_7 = PyFloat_AsDouble(__pyx_v_x); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 235; goto __pyx_L1;}
    __pyx_8 = PyFloat_AsDouble(__pyx_v_y); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 235; goto __pyx_L1;}
    __pyx_9 = PyFloat_AsDouble(__pyx_v_z); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 235; goto __pyx_L1;}
    glVertex3f(__pyx_7,__pyx_8,__pyx_9);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":236 */
    glTexCoord2f(1,(-1));

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":237 */
    __pyx_7 = PyFloat_AsDouble(__pyx_v_x); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 237; goto __pyx_L1;}
    __pyx_8 = PyFloat_AsDouble(__pyx_v_y); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 237; goto __pyx_L1;}
    __pyx_9 = PyFloat_AsDouble(__pyx_v_z); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 237; goto __pyx_L1;}
    glVertex3f(__pyx_7,__pyx_8,__pyx_9);
    __pyx_L7:;
  }

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":239 */
  __pyx_5 = (__pyx_v_clipping == 1);
  if (__pyx_5) {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":240 */
    for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_numexclude; ++__pyx_v_i) {

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":241 */
      __pyx_v_index = (__pyx_v_excl[__pyx_v_i]);

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":242 */
      __pyx_3 = PyFloat_FromDouble((__pyx_v_vert[((__pyx_v_index * __pyx_v_stride1) + (__pyx_v_stride2 * 0))])); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 242; goto __pyx_L1;}
      Py_DECREF(__pyx_v_x);
      __pyx_v_x = __pyx_3;
      __pyx_3 = 0;

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":243 */
      __pyx_2 = PyFloat_FromDouble((__pyx_v_vert[((__pyx_v_index * __pyx_v_stride1) + (__pyx_v_stride2 * 1))])); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 243; goto __pyx_L1;}
      Py_DECREF(__pyx_v_y);
      __pyx_v_y = __pyx_2;
      __pyx_2 = 0;

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":244 */
      __pyx_4 = PyFloat_FromDouble((__pyx_v_vert[((__pyx_v_index * __pyx_v_stride1) + (__pyx_v_stride2 * 2))])); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 244; goto __pyx_L1;}
      Py_DECREF(__pyx_v_z);
      __pyx_v_z = __pyx_4;
      __pyx_4 = 0;

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":245 */
      __pyx_v_r = (__pyx_v_rad[__pyx_v_index]);

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":246 */
      __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_GL_TEXTURE1_ARB); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 246; goto __pyx_L1;}
      __pyx_6 = PyInt_AsUnsignedLongMask(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 246; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      glMultiTexCoord2fARB(__pyx_6,(__pyx_v_r + __pyx_v_s),(((__pyx_v_r + __pyx_v_s) * (__pyx_v_r + __pyx_v_s)) / ((__pyx_v_s * __pyx_v_s) + ((2 * __pyx_v_r) * __pyx_v_s))));

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":248 */
      glTexCoord2f(1,1);

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":249 */
      __pyx_7 = PyFloat_AsDouble(__pyx_v_x); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 249; goto __pyx_L1;}
      __pyx_8 = PyFloat_AsDouble(__pyx_v_y); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 249; goto __pyx_L1;}
      __pyx_9 = PyFloat_AsDouble(__pyx_v_z); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 249; goto __pyx_L1;}
      glVertex3f(__pyx_7,__pyx_8,__pyx_9);

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":250 */
      glTexCoord2f((-1),1);

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":251 */
      __pyx_7 = PyFloat_AsDouble(__pyx_v_x); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 251; goto __pyx_L1;}
      __pyx_8 = PyFloat_AsDouble(__pyx_v_y); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 251; goto __pyx_L1;}
      __pyx_9 = PyFloat_AsDouble(__pyx_v_z); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 251; goto __pyx_L1;}
      glVertex3f(__pyx_7,__pyx_8,__pyx_9);

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":252 */
      glTexCoord2f((-1),(-1));

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":253 */
      __pyx_7 = PyFloat_AsDouble(__pyx_v_x); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 253; goto __pyx_L1;}
      __pyx_8 = PyFloat_AsDouble(__pyx_v_y); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 253; goto __pyx_L1;}
      __pyx_9 = PyFloat_AsDouble(__pyx_v_z); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 253; goto __pyx_L1;}
      glVertex3f(__pyx_7,__pyx_8,__pyx_9);

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":254 */
      glTexCoord2f(1,(-1));

      /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":255 */
      __pyx_7 = PyFloat_AsDouble(__pyx_v_x); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 255; goto __pyx_L1;}
      __pyx_8 = PyFloat_AsDouble(__pyx_v_y); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 255; goto __pyx_L1;}
      __pyx_9 = PyFloat_AsDouble(__pyx_v_z); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 255; goto __pyx_L1;}
      glVertex3f(__pyx_7,__pyx_8,__pyx_9);
    }
    goto __pyx_L11;
  }
  __pyx_L11:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("molGL.MolDrawHalo");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_x);
  Py_DECREF(__pyx_v_y);
  Py_DECREF(__pyx_v_z);
  Py_DECREF(__pyx_v_coords);
  Py_DECREF(__pyx_v_radii);
  Py_DECREF(__pyx_v_clipplane);
  Py_DECREF(__pyx_v_exclude);
  Py_DECREF(__pyx_v_indices);
  return __pyx_r;
}

static PyObject *__pyx_k10p;

static char (__pyx_k10[]) = "conf must be a sequence of 3 dimensional coordinates";

static PyObject *__pyx_f_5molGL_MolDrawOnTexture(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5molGL_MolDrawOnTexture(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyArrayObject *__pyx_v_coords = 0;
  PyArrayObject *__pyx_v_radii = 0;
  PyArrayObject *__pyx_v_textures = 0;
  int __pyx_v_CSIZE;
  PyArrayObject *__pyx_v_indices = 0;
  int __pyx_v_i;
  int __pyx_v_index;
  int __pyx_v_numindices;
  int __pyx_v_stride1;
  int __pyx_v_stride2;
  int (*__pyx_v_idx);
  float (*__pyx_v_vert);
  float (*__pyx_v_rad);
  float (*__pyx_v_tex);
  int __pyx_v_noindices;
  float __pyx_v_h;
  float __pyx_v_Xm;
  float __pyx_v_Xp;
  float __pyx_v_Ym;
  float __pyx_v_Yp;
  float __pyx_v_tx;
  float __pyx_v_ty;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  unsigned int __pyx_5;
  static char *__pyx_argnames[] = {"coords","radii","textures","CSIZE","indices",0};
  __pyx_v_indices = __pyx_k5;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOOi|O", __pyx_argnames, &__pyx_v_coords, &__pyx_v_radii, &__pyx_v_textures, &__pyx_v_CSIZE, &__pyx_v_indices)) return 0;
  Py_INCREF(__pyx_v_coords);
  Py_INCREF(__pyx_v_radii);
  Py_INCREF(__pyx_v_textures);
  Py_INCREF(__pyx_v_indices);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_coords), __pyx_ptype_5molGL_ndarray, 1, "coords")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 257; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_radii), __pyx_ptype_5molGL_ndarray, 1, "radii")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 257; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_textures), __pyx_ptype_5molGL_ndarray, 1, "textures")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 257; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_indices), __pyx_ptype_5molGL_ndarray, 1, "indices")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 257; goto __pyx_L1;}

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":265 */
  __pyx_v_vert = ((float (*))__pyx_v_coords->data);

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":266 */
  __pyx_v_rad = ((float (*))__pyx_v_radii->data);

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":267 */
  __pyx_v_tex = ((float (*))__pyx_v_textures->data);

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":269 */
  __pyx_1 = (__pyx_v_coords->nd != 2);
  if (__pyx_1) {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":270 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_Exception); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 270; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 270; goto __pyx_L1;}
    Py_INCREF(__pyx_k10p);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_k10p);
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 270; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_4, 0, 0);
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 270; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":271 */
  __pyx_1 = ((__pyx_v_coords->dimensions[1]) == 3);
  if (__pyx_1) {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":272 */
    __pyx_v_stride1 = ((__pyx_v_coords->strides[0]) / (sizeof(float )));

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":273 */
    __pyx_v_stride2 = ((__pyx_v_coords->strides[1]) / (sizeof(float )));
    goto __pyx_L3;
  }
  /*else*/ {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":275 */
    __pyx_v_stride1 = ((__pyx_v_coords->strides[1]) / (sizeof(float )));

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":276 */
    __pyx_v_stride2 = ((__pyx_v_coords->strides[0]) / (sizeof(float )));
  }
  __pyx_L3:;

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":278 */
  __pyx_1 = __pyx_v_indices == Py_None;
  if (__pyx_1) {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":279 */
    __pyx_1 = ((__pyx_v_coords->dimensions[1]) == 3);
    if (__pyx_1) {
      __pyx_v_numindices = (__pyx_v_coords->dimensions[0]);
      goto __pyx_L5;
    }
    /*else*/ {
      __pyx_v_numindices = (__pyx_v_coords->dimensions[1]);
    }
    __pyx_L5:;

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":281 */
    __pyx_v_noindices = 0;
    goto __pyx_L4;
  }
  /*else*/ {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":283 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 283; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 283; goto __pyx_L1;}
    Py_INCREF(((PyObject *)__pyx_v_indices));
    PyTuple_SET_ITEM(__pyx_3, 0, ((PyObject *)__pyx_v_indices));
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 283; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_1 = PyInt_AsLong(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 283; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_v_numindices = __pyx_1;

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":284 */
    __pyx_v_idx = ((int (*))__pyx_v_indices->data);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":285 */
    __pyx_v_noindices = 1;
  }
  __pyx_L4:;

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":287 */
  __pyx_v_h = 0;

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":288 */
  __pyx_v_Xm = ((-1.0) - (1.0 / __pyx_v_CSIZE));

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":289 */
  __pyx_v_Xp = (1.0 + (1.0 / __pyx_v_CSIZE));

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":290 */
  __pyx_v_Ym = __pyx_v_Xm;

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":291 */
  __pyx_v_Yp = __pyx_v_Xp;

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":293 */
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_numindices; ++__pyx_v_i) {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":294 */
    __pyx_1 = (__pyx_v_noindices == 0);
    if (__pyx_1) {
      __pyx_v_index = __pyx_v_i;
      goto __pyx_L8;
    }
    /*else*/ {
      __pyx_v_index = (__pyx_v_idx[__pyx_v_i]);
    }
    __pyx_L8:;

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":297 */
    __pyx_v_tx = (__pyx_v_tex[((__pyx_v_index * 2) + 0)]);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":298 */
    __pyx_v_ty = (__pyx_v_tex[((__pyx_v_index * 2) + 1)]);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":300 */
    glColor3f(myrand(),myrand(),myrand());

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":302 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_GL_TEXTURE1_ARB); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 302; goto __pyx_L1;}
    __pyx_5 = PyInt_AsUnsignedLongMask(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 302; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    glMultiTexCoord4fARB(__pyx_5,(__pyx_v_vert[((__pyx_v_index * __pyx_v_stride1) + (__pyx_v_stride2 * 0))]),(__pyx_v_vert[((__pyx_v_index * __pyx_v_stride1) + (__pyx_v_stride2 * 1))]),(__pyx_v_vert[((__pyx_v_index * __pyx_v_stride1) + (__pyx_v_stride2 * 2))]),(__pyx_v_rad[__pyx_v_index]));

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":303 */
    glTexCoord2f(__pyx_v_Xm,__pyx_v_Ym);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":303 */
    glVertex2f(((-__pyx_v_h) + __pyx_v_tx),((-__pyx_v_h) + __pyx_v_ty));

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":304 */
    glTexCoord2f(__pyx_v_Xp,__pyx_v_Ym);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":304 */
    glVertex2f((((-__pyx_v_h) + __pyx_v_tx) + __pyx_v_CSIZE),((-__pyx_v_h) + __pyx_v_ty));

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":305 */
    glTexCoord2f(__pyx_v_Xp,__pyx_v_Yp);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":305 */
    glVertex2f((((-__pyx_v_h) + __pyx_v_tx) + __pyx_v_CSIZE),(((-__pyx_v_h) + __pyx_v_ty) + __pyx_v_CSIZE));

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":306 */
    glTexCoord2f(__pyx_v_Xm,__pyx_v_Yp);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":306 */
    glVertex2f(((-__pyx_v_h) + __pyx_v_tx),(((-__pyx_v_h) + __pyx_v_ty) + __pyx_v_CSIZE));
  }

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("molGL.MolDrawOnTexture");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_coords);
  Py_DECREF(__pyx_v_radii);
  Py_DECREF(__pyx_v_textures);
  Py_DECREF(__pyx_v_indices);
  return __pyx_r;
}

static PyObject *__pyx_k11p;

static char (__pyx_k11[]) = "conf must be a sequence of 3 dimensional coordinates";

static PyObject *__pyx_f_5molGL_molDrawSticks(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5molGL_molDrawSticks(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyArrayObject *__pyx_v_coords = 0;
  PyArrayObject *__pyx_v_bonds = 0;
  PyArrayObject *__pyx_v_colors = 0;
  PyArrayObject *__pyx_v_clipplane = 0;
  PyArrayObject *__pyx_v_indices = 0;
  int __pyx_v_i;
  int __pyx_v_index;
  int __pyx_v_nbonds;
  int __pyx_v_numindices;
  int __pyx_v_stride1;
  int __pyx_v_stride2;
  int (*__pyx_v_idx);
  int (*__pyx_v_bnds);
  float (*__pyx_v_vert);
  float (*__pyx_v_col);
  float __pyx_v_x;
  float __pyx_v_y;
  float __pyx_v_z;
  int __pyx_v_noindices;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"coords","bonds","colors","clipplane","indices",0};
  __pyx_v_indices = __pyx_k6;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOOO|O", __pyx_argnames, &__pyx_v_coords, &__pyx_v_bonds, &__pyx_v_colors, &__pyx_v_clipplane, &__pyx_v_indices)) return 0;
  Py_INCREF(__pyx_v_coords);
  Py_INCREF(__pyx_v_bonds);
  Py_INCREF(__pyx_v_colors);
  Py_INCREF(__pyx_v_clipplane);
  Py_INCREF(__pyx_v_indices);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_coords), __pyx_ptype_5molGL_ndarray, 1, "coords")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 308; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_bonds), __pyx_ptype_5molGL_ndarray, 1, "bonds")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 308; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_colors), __pyx_ptype_5molGL_ndarray, 1, "colors")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 308; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_clipplane), __pyx_ptype_5molGL_ndarray, 1, "clipplane")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 308; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_indices), __pyx_ptype_5molGL_ndarray, 1, "indices")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 308; goto __pyx_L1;}

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":317 */
  __pyx_v_vert = ((float (*))__pyx_v_coords->data);

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":318 */
  __pyx_v_col = ((float (*))__pyx_v_colors->data);

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":319 */
  __pyx_v_bnds = ((int (*))__pyx_v_bonds->data);

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":321 */
  __pyx_1 = (__pyx_v_coords->nd != 2);
  if (__pyx_1) {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":322 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_Exception); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 322; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 322; goto __pyx_L1;}
    Py_INCREF(__pyx_k11p);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_k11p);
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 322; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_4, 0, 0);
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 322; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":323 */
  __pyx_1 = ((__pyx_v_coords->dimensions[1]) == 3);
  if (__pyx_1) {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":324 */
    __pyx_v_stride1 = ((__pyx_v_coords->strides[0]) / (sizeof(float )));

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":325 */
    __pyx_v_stride2 = ((__pyx_v_coords->strides[1]) / (sizeof(float )));
    goto __pyx_L3;
  }
  /*else*/ {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":327 */
    __pyx_v_stride1 = ((__pyx_v_coords->strides[1]) / (sizeof(float )));

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":328 */
    __pyx_v_stride2 = ((__pyx_v_coords->strides[0]) / (sizeof(float )));
  }
  __pyx_L3:;

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":330 */
  __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 330; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 330; goto __pyx_L1;}
  Py_INCREF(((PyObject *)__pyx_v_bonds));
  PyTuple_SET_ITEM(__pyx_3, 0, ((PyObject *)__pyx_v_bonds));
  __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 330; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_1 = PyInt_AsLong(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 330; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_v_nbonds = __pyx_1;

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":332 */
  __pyx_1 = __pyx_v_indices == Py_None;
  if (__pyx_1) {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":333 */
    __pyx_1 = ((__pyx_v_coords->dimensions[1]) == 3);
    if (__pyx_1) {
      __pyx_v_numindices = (__pyx_v_coords->dimensions[0]);
      goto __pyx_L5;
    }
    /*else*/ {
      __pyx_v_numindices = (__pyx_v_coords->dimensions[1]);
    }
    __pyx_L5:;

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":335 */
    __pyx_v_noindices = 0;
    goto __pyx_L4;
  }
  /*else*/ {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":337 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 337; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 337; goto __pyx_L1;}
    Py_INCREF(((PyObject *)__pyx_v_indices));
    PyTuple_SET_ITEM(__pyx_3, 0, ((PyObject *)__pyx_v_indices));
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 337; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_1 = PyInt_AsLong(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 337; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_v_numindices = __pyx_1;

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":338 */
    __pyx_v_idx = ((int (*))__pyx_v_indices->data);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":339 */
    __pyx_v_noindices = 1;
  }
  __pyx_L4:;

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":348 */
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_nbonds; ++__pyx_v_i) {

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":352 */
    __pyx_v_index = (__pyx_v_bnds[((__pyx_v_i * 2) + 0)]);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":353 */
    __pyx_v_x = (__pyx_v_vert[((__pyx_v_index * __pyx_v_stride1) + (__pyx_v_stride2 * 0))]);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":354 */
    __pyx_v_y = (__pyx_v_vert[((__pyx_v_index * __pyx_v_stride1) + (__pyx_v_stride2 * 1))]);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":355 */
    __pyx_v_z = (__pyx_v_vert[((__pyx_v_index * __pyx_v_stride1) + (__pyx_v_stride2 * 2))]);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":357 */
    glColor3f((__pyx_v_col[((__pyx_v_index * 3) + 0)]),(__pyx_v_col[((__pyx_v_index * 3) + 1)]),(__pyx_v_col[((__pyx_v_index * 3) + 2)]));

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":358 */
    glVertex3f(__pyx_v_x,__pyx_v_y,__pyx_v_z);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":359 */
    __pyx_v_index = (__pyx_v_bnds[((__pyx_v_i * 2) + 1)]);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":360 */
    __pyx_v_x = (__pyx_v_vert[((__pyx_v_index * __pyx_v_stride1) + (__pyx_v_stride2 * 0))]);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":361 */
    __pyx_v_y = (__pyx_v_vert[((__pyx_v_index * __pyx_v_stride1) + (__pyx_v_stride2 * 1))]);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":362 */
    __pyx_v_z = (__pyx_v_vert[((__pyx_v_index * __pyx_v_stride1) + (__pyx_v_stride2 * 2))]);

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":363 */
    glColor3f((__pyx_v_col[((__pyx_v_index * 3) + 0)]),(__pyx_v_col[((__pyx_v_index * 3) + 1)]),(__pyx_v_col[((__pyx_v_index * 3) + 2)]));

    /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":364 */
    glVertex3f(__pyx_v_x,__pyx_v_y,__pyx_v_z);
  }

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("molGL.molDrawSticks");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_coords);
  Py_DECREF(__pyx_v_bonds);
  Py_DECREF(__pyx_v_colors);
  Py_DECREF(__pyx_v_clipplane);
  Py_DECREF(__pyx_v_indices);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_Exception, "Exception"},
  {&__pyx_n_GL_TEXTURE0_ARB, "GL_TEXTURE0_ARB"},
  {&__pyx_n_GL_TEXTURE1_ARB, "GL_TEXTURE1_ARB"},
  {&__pyx_n_MolDraw, "MolDraw"},
  {&__pyx_n_MolDrawHalo, "MolDrawHalo"},
  {&__pyx_n_MolDrawOnTexture, "MolDrawOnTexture"},
  {&__pyx_n_MolDrawShadow, "MolDrawShadow"},
  {&__pyx_n_allclose, "allclose"},
  {&__pyx_n_len, "len"},
  {&__pyx_n_molDrawSticks, "molDrawSticks"},
  {&__pyx_n_numpy, "numpy"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k7p, __pyx_k7, sizeof(__pyx_k7)},
  {&__pyx_k8p, __pyx_k8, sizeof(__pyx_k8)},
  {&__pyx_k9p, __pyx_k9, sizeof(__pyx_k9)},
  {&__pyx_k10p, __pyx_k10, sizeof(__pyx_k10)},
  {&__pyx_k11p, __pyx_k11, sizeof(__pyx_k11)},
  {0, 0, 0}
};

static struct PyMethodDef __pyx_methods[] = {
  {"MolDraw", (PyCFunction)__pyx_f_5molGL_MolDraw, METH_VARARGS|METH_KEYWORDS, 0},
  {"MolDrawShadow", (PyCFunction)__pyx_f_5molGL_MolDrawShadow, METH_VARARGS|METH_KEYWORDS, 0},
  {"MolDrawHalo", (PyCFunction)__pyx_f_5molGL_MolDrawHalo, METH_VARARGS|METH_KEYWORDS, 0},
  {"MolDrawOnTexture", (PyCFunction)__pyx_f_5molGL_MolDrawOnTexture, METH_VARARGS|METH_KEYWORDS, 0},
  {"molDrawSticks", (PyCFunction)__pyx_f_5molGL_molDrawSticks, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initmolGL(void); /*proto*/
PyMODINIT_FUNC initmolGL(void) {
  PyObject *__pyx_1 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("molGL", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  __pyx_ptype_5molGL_ndarray = __Pyx_ImportType("numpy", "ndarray", sizeof(PyArrayObject)); if (!__pyx_ptype_5molGL_ndarray) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 6; goto __pyx_L1;}

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":33 */
  __pyx_1 = PyInt_FromLong(0x84C0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_GL_TEXTURE0_ARB, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":34 */
  __pyx_1 = PyInt_FromLong(0x84C1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_GL_TEXTURE1_ARB, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":36 */
  __pyx_1 = __Pyx_Import(__pyx_n_numpy, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_numpy, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":38 */
  Py_INCREF(Py_None);
  __pyx_k2 = ((PyArrayObject *)Py_None);

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":115 */
  Py_INCREF(Py_None);
  __pyx_k3 = ((PyArrayObject *)Py_None);

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":181 */
  Py_INCREF(Py_None);
  __pyx_k4 = ((PyArrayObject *)Py_None);

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":257 */
  Py_INCREF(Py_None);
  __pyx_k5 = ((PyArrayObject *)Py_None);

  /* "/Users/Naveen/Projects/python/renderer.balls/pyQutemol/src/molGL.pyx":308 */
  Py_INCREF(Py_None);
  __pyx_k6 = ((PyArrayObject *)Py_None);
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("molGL");
}

static char *__pyx_filenames[] = {
  "molGL.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if ((none_allowed && obj == Py_None) || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError,
        "Argument '%s' has incorrect type (expected %s, got %s)",
        name, type->tp_name, obj->ob_type->tp_name);
    return 0;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    /* Next, repeatedly, replace a tuple exception with its first item */
    while (PyTuple_Check(type) && PyTuple_Size(type) > 0) {
        PyObject *tmp = type;
        type = PyTuple_GET_ITEM(type, 0);
        Py_INCREF(type);
        Py_DECREF(tmp);
    }
    if (PyString_Check(type)) {
        if (PyErr_Warn(PyExc_DeprecationWarning,
                "raising a string exception is deprecated"))
            goto raise_error;
    }
    else if (PyType_Check(type) || PyClass_Check(type))
        ; /*PyErr_NormalizeException(&type, &value, &tb);*/
    else {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        if (PyInstance_Check(type))
            type = (PyObject*) ((PyInstanceObject*)type)->in_class;
        else
            type = (PyObject*) type->ob_type;
        Py_INCREF(type);
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, 
    long size) 
{
    PyObject *py_module_name = 0;
    PyObject *py_class_name = 0;
    PyObject *py_name_list = 0;
    PyObject *py_module = 0;
    PyObject *result = 0;
    
    py_module_name = PyString_FromString(module_name);
    if (!py_module_name)
        goto bad;
    py_class_name = PyString_FromString(class_name);
    if (!py_class_name)
        goto bad;
    py_name_list = PyList_New(1);
    if (!py_name_list)
        goto bad;
    Py_INCREF(py_class_name);
    if (PyList_SetItem(py_name_list, 0, py_class_name) < 0)
        goto bad;
    py_module = __Pyx_Import(py_module_name, py_name_list);
    if (!py_module)
        goto bad;
    result = PyObject_GetAttr(py_module, py_class_name);
    if (!result)
        goto bad;
    if (!PyType_Check(result)) {
        PyErr_Format(PyExc_TypeError, 
            "%s.%s is not a type object",
            module_name, class_name);
        goto bad;
    }
    if (((PyTypeObject *)result)->tp_basicsize != size) {
        PyErr_Format(PyExc_ValueError, 
            "%s.%s does not appear to be the correct type object",
            module_name, class_name);
        goto bad;
    }
    goto done;
bad:
    Py_XDECREF(result);
    result = 0;
done:
    Py_XDECREF(py_module_name);
    Py_XDECREF(py_class_name);
    Py_XDECREF(py_name_list);
    return (PyTypeObject *)result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
